# Generated by Django 5.2.6 on 2025-09-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('fitness', 'Fitness Equipment'), ('outdoor', 'Outdoor & Camping'), ('swimming', 'Swimming Gear'), ('badminton', 'Badminton Equipment'), ('basketball', 'Basketball Gear'), ('cycling', 'Cycling'), ('yoga', 'Yoga & Pilates'), ('running', 'Running Shoes & Apparel'), ('sportswear', 'Sportswear'), ('supplements', 'Supplements & Nutrition')], default='sportswear', max_length=30)
        ),
    ]