# Generated by Django 5.2.6 on 2025-09-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('fitness', 'Fitness Equipment'), ('outdoor', 'Outdoor & Camping'), ('swimming', 'Swimming Gear'), ('badminton', 'Badminton Equipment'), ('basketball', 'Basketball Gear'), ('cycling', 'Cycling'), ('yoga', 'Yoga & Pilates'), ('running', 'Running Shoes & Apparel'), ('sportswear', 'Sportswear'), ('supplements', 'Supplements & Nutrition')], default='sportswear', max_length=30)
        ),
    ]